"""empty message

Revision ID: a4f5a066b84c
Revises: 46e00fa23a5a
Create Date: 2023-01-20 13:17:13.565655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4f5a066b84c'
down_revision = '46e00fa23a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('key', table_name='devices2')
    op.drop_index('name', table_name='devices2')
    op.drop_table('devices2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices2',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='devices2_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'devices2', ['name'], unique=False)
    op.create_index('key', 'devices2', ['key'], unique=False)
    # ### end Alembic commands ###
