"""empty message

Revision ID: f0ab10e27c4f
Revises: a4f5a066b84c
Create Date: 2023-01-26 00:03:54.611054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ab10e27c4f'
down_revision = 'a4f5a066b84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dir_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Min', sa.Float(), nullable=True),
    sa.Column('Max', sa.Float(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Directory_Id', sa.Integer(), nullable=True),
    sa.Column('Sensor_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Directory_Id'], ['directory.id'], ),
    sa.ForeignKeyConstraint(['Sensor_Id'], ['dir_sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_dir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['directory_id'], ['directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Range_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Range_Id'], ['range.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Content', sa.String(length=200), nullable=True),
    sa.Column('Problem_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Problem_Id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice')
    op.drop_table('problem')
    op.drop_table('dev_dir')
    op.drop_table('range')
    op.drop_table('directory')
    op.drop_table('dir_sensor')
    # ### end Alembic commands ###
